# Generated by Django 6.0.7 on 2026-07-15 19:44

import challenge.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('ville', models.CharField(blank=True, max_length=150)),
                ('code_club_ffta', models.CharField(blank=True, max_length=20, verbose_name='Code club FFTA')),
            ],
            options={
                'verbose_name': 'Club',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Archer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('licence_ffta', models.CharField(max_length=20, unique=True, verbose_name='N° licence FFTA')),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('type_arc', models.CharField(choices=[('AL', 'Arc Libre'), ('APN', 'Arc à Poulies Nu'), ('AN', 'Arc Nu (Barebow)'), ('AD', 'Arc Droit'), ('AC', 'Arc Chasse')], max_length=4, verbose_name="Type d'arc")),
                ('actif', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archers', to='challenge.club')),
            ],
            options={
                'verbose_name': 'Archer',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Manche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('saison', models.PositiveIntegerField(default=challenge.models._annee_courante)),
                ('validee', models.BooleanField(default=False, verbose_name='Validée par le comité régional')),
                ('nb_cibles', models.PositiveIntegerField(default=21)),
                ('club_organisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manches_organisees', to='challenge.club')),
            ],
            options={
                'verbose_name': 'Manche',
                'verbose_name_plural': 'Manches',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('disqualifie', models.BooleanField(default=False)),
                ('rang_categorie', models.PositiveIntegerField(blank=True, null=True)),
                ('points_classement', models.PositiveIntegerField(blank=True, null=True)),
                ('archer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='challenge.archer')),
                ('manche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='challenge.manche')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'ordering': ['manche', '-score'],
                'unique_together': {('manche', 'archer')},
            },
        ),
    ]
